import type { EditorThemeClasses } from 'lexical';

import './CorvusTheme.css';

const theme: EditorThemeClasses = {
	blockCursor: 'CorvusTheme__blockCursor',
	characterLimit: 'CorvusTheme__characterLimit',
	code: 'CorvusTheme__code',
	codeHighlight: {
		atrule: 'CorvusTheme__tokenAttr',
		attr: 'CorvusTheme__tokenAttr',
		boolean: 'CorvusTheme__tokenProperty',
		builtin: 'CorvusTheme__tokenSelector',
		cdata: 'CorvusTheme__tokenComment',
		char: 'CorvusTheme__tokenSelector',
		class: 'CorvusTheme__tokenFunction',
		'class-name': 'CorvusTheme__tokenFunction',
		comment: 'CorvusTheme__tokenComment',
		constant: 'CorvusTheme__tokenProperty',
		deleted: 'CorvusTheme__tokenProperty',
		doctype: 'CorvusTheme__tokenComment',
		entity: 'CorvusTheme__tokenOperator',
		function: 'CorvusTheme__tokenFunction',
		important: 'CorvusTheme__tokenVariable',
		inserted: 'CorvusTheme__tokenSelector',
		keyword: 'CorvusTheme__tokenAttr',
		namespace: 'CorvusTheme__tokenVariable',
		number: 'CorvusTheme__tokenProperty',
		operator: 'CorvusTheme__tokenOperator',
		prolog: 'CorvusTheme__tokenComment',
		property: 'CorvusTheme__tokenProperty',
		punctuation: 'CorvusTheme__tokenPunctuation',
		regex: 'CorvusTheme__tokenVariable',
		selector: 'CorvusTheme__tokenSelector',
		string: 'CorvusTheme__tokenSelector',
		symbol: 'CorvusTheme__tokenProperty',
		tag: 'CorvusTheme__tokenProperty',
		url: 'CorvusTheme__tokenOperator',
		variable: 'CorvusTheme__tokenVariable',
	},
	embedBlock: {
		base: 'CorvusTheme__embedBlock',
		focus: 'CorvusTheme__embedBlockFocus',
	},
	hashtag: 'CorvusTheme__hashtag',
	heading: {
		h1: 'CorvusTheme__h1',
		h2: 'CorvusTheme__h2',
		h3: 'CorvusTheme__h3',
		h4: 'CorvusTheme__h4',
		h5: 'CorvusTheme__h5',
		h6: 'CorvusTheme__h6',
	},
	image: 'editor-image',
	indent: 'CorvusTheme__indent',
	inlineImage: 'inline-editor-image',
	layoutContainer: 'CorvusTheme__layoutContainer',
	layoutItem: 'CorvusTheme__layoutItem',
	link: 'CorvusTheme__link',
	list: {
		checklist: 'CorvusTheme__checklist',
		listitem: 'CorvusTheme__listItem',
		listitemChecked: 'CorvusTheme__listItemChecked',
		listitemUnchecked: 'CorvusTheme__listItemUnchecked',
		nested: {
			listitem: 'CorvusTheme__nestedListItem',
		},
		olDepth: [
			'CorvusTheme__ol1',
			'CorvusTheme__ol2',
			'CorvusTheme__ol3',
			'CorvusTheme__ol4',
			'CorvusTheme__ol5',
		],
		ul: 'CorvusTheme__ul',
	},
	ltr: 'CorvusTheme__ltr',
	mark: 'CorvusTheme__mark',
	markOverlap: 'CorvusTheme__markOverlap',
	paragraph: 'CorvusTheme__paragraph',
	quote: 'CorvusTheme__quote',
	rtl: 'CorvusTheme__rtl',
	table: 'CorvusTheme__table',
	tableAddColumns: 'CorvusTheme__tableAddColumns',
	tableAddRows: 'CorvusTheme__tableAddRows',
	tableCell: 'CorvusTheme__tableCell',
	tableCellActionButton: 'CorvusTheme__tableCellActionButton',
	tableCellActionButtonContainer: 'CorvusTheme__tableCellActionButtonContainer',
	tableCellEditing: 'CorvusTheme__tableCellEditing',
	tableCellHeader: 'CorvusTheme__tableCellHeader',
	tableCellPrimarySelected: 'CorvusTheme__tableCellPrimarySelected',
	tableCellResizer: 'CorvusTheme__tableCellResizer',
	tableCellSelected: 'CorvusTheme__tableCellSelected',
	tableCellSortedIndicator: 'CorvusTheme__tableCellSortedIndicator',
	tableResizeRuler: 'CorvusTheme__tableCellResizeRuler',
	tableSelected: 'CorvusTheme__tableSelected',
	tableSelection: 'CorvusTheme__tableSelection',
	text: {
		bold: 'CorvusTheme__textBold',
		code: 'CorvusTheme__textCode',
		italic: 'CorvusTheme__textItalic',
		strikethrough: 'CorvusTheme__textStrikethrough',
		subscript: 'CorvusTheme__textSubscript',
		superscript: 'CorvusTheme__textSuperscript',
		underline: 'CorvusTheme__textUnderline',
		underlineStrikethrough: 'CorvusTheme__textUnderlineStrikethrough',
	},
};

export default theme;
